// ─── Mock Users ────────────────────────────────────────────────────────────────
export const MOCK_USERS = [
  { id: "u1", name: "田中 太郎", initials: "田", color: "#3b82f6" },
  { id: "u2", name: "佐藤 花子", initials: "佐", color: "#8b5cf6" },
  { id: "u3", name: "鈴木 一郎", initials: "鈴", color: "#10b981" },
];

export const CURRENT_USER = MOCK_USERS[0];

// ─── Mock Groups ──────────────────────────────────────────────────────────────
export const MOCK_GROUPS = [
  {
    id: "g1",
    name: "全社アナウンス",
    type: "board" as const,
    icon: "📢",
    unread: 3,
    updatedAt: "2025-05-08 09:30",
    lastMessage: "5月の全社会議について",
  },
  {
    id: "g2",
    name: "開発チーム",
    type: "board" as const,
    icon: "💻",
    unread: 0,
    updatedAt: "2025-05-07 18:45",
    lastMessage: "スプリントレビューの議事録",
  },
  {
    id: "g3",
    name: "雑談ルーム",
    type: "chat" as const,
    icon: "💬",
    unread: 12,
    updatedAt: "2025-05-08 10:05",
    lastMessage: "おはようございます！",
  },
];

// ─── Mock Board Posts ─────────────────────────────────────────────────────────
export const MOCK_POSTS = [
  {
    id: "p1",
    groupId: "g1",
    author: MOCK_USERS[1],
    createdAt: "2025-05-08 09:30",
    body: "5月の全社会議について\n\n来週木曜日14時より、大会議室にて全社会議を実施します。\n各部署からの報告事項をまとめて提出してください。",
    imageUrl: null,
    reactions: { "👍": 8, "❤️": 3, "😮": 1 },
    commentCount: 5,
  },
  {
    id: "p2",
    groupId: "g1",
    author: MOCK_USERS[2],
    createdAt: "2025-05-07 16:20",
    body: "社内ドレスコードの変更について\n\n6月よりカジュアルフライデーを毎週金曜日に導入します。詳細はHRポータルをご確認ください。",
    imageUrl: null,
    reactions: { "👍": 15, "❤️": 7, "😮": 2 },
    commentCount: 11,
  },
  {
    id: "p3",
    groupId: "g2",
    author: MOCK_USERS[0],
    createdAt: "2025-05-07 18:45",
    body: "スプリント22 レビュー議事録\n\nベロシティ: 48pt (計画比 +12%)\n完了タスク: 18件\n持ち越し: 3件（詳細は添付参照）",
    imageUrl: null,
    reactions: { "👍": 4, "❤️": 0, "😮": 0 },
    commentCount: 2,
  },
  {
    id: "p4",
    groupId: "g2",
    author: MOCK_USERS[1],
    createdAt: "2025-05-06 11:00",
    body: "新しいデザインシステムのプレビューです。フィードバックをいただけると嬉しいです！",
    imageUrl: "/mock-post-image.jpg",
    reactions: { "👍": 6, "❤️": 9, "😮": 4 },
    commentCount: 8,
  },
  {
    id: "p5",
    groupId: "g2",
    author: MOCK_USERS[2],
    createdAt: "2025-05-05 09:15",
    body: "本番環境のデプロイが完了しました。v2.4.1リリースノートは以下の通りです:\n\n- バグ修正: ログインループの問題を解消\n- パフォーマンス改善: API応答速度 30% 向上\n- 新機能: ダークモード対応",
    imageUrl: null,
    reactions: { "👍": 12, "❤️": 5, "😮": 0 },
    commentCount: 3,
  },
];

// ─── Mock Chat Messages ───────────────────────────────────────────────────────
export const MOCK_MESSAGES = [
  {
    id: "m1",
    groupId: "g3",
    author: MOCK_USERS[1],
    createdAt: "10:00",
    text: "おはようございます！",
    imageUrl: null,
    isOwn: false,
  },
  {
    id: "m2",
    groupId: "g3",
    author: MOCK_USERS[2],
    createdAt: "10:01",
    text: "おはようございます！今日もよろしくお願いします。",
    imageUrl: null,
    isOwn: false,
  },
  {
    id: "m3",
    groupId: "g3",
    author: MOCK_USERS[0],
    createdAt: "10:03",
    text: "おはようございます！昨日の会議の件ですが、資料の確認をお願いできますか？",
    imageUrl: null,
    isOwn: true,
  },
  {
    id: "m4",
    groupId: "g3",
    author: MOCK_USERS[1],
    createdAt: "10:05",
    text: "了解しました！今日中に確認します。",
    imageUrl: null,
    isOwn: false,
  },
  {
    id: "m5",
    groupId: "g3",
    author: MOCK_USERS[2],
    createdAt: "10:08",
    text: "私も後で確認します。",
    imageUrl: null,
    isOwn: false,
  },
  {
    id: "m6",
    groupId: "g3",
    author: MOCK_USERS[0],
    createdAt: "10:10",
    text: "ありがとうございます！",
    imageUrl: null,
    isOwn: true,
  },
  {
    id: "m7",
    groupId: "g3",
    author: MOCK_USERS[1],
    createdAt: "10:25",
    text: "ランチどこ行きますか？",
    imageUrl: null,
    isOwn: false,
  },
  {
    id: "m8",
    groupId: "g3",
    author: MOCK_USERS[2],
    createdAt: "10:26",
    text: "いつものラーメン屋はどうですか？",
    imageUrl: null,
    isOwn: false,
  },
  {
    id: "m9",
    groupId: "g3",
    author: MOCK_USERS[0],
    createdAt: "10:28",
    text: "賛成です！12時でいいですか？",
    imageUrl: null,
    isOwn: true,
  },
  {
    id: "m10",
    groupId: "g3",
    author: MOCK_USERS[1],
    createdAt: "10:29",
    text: "12時で大丈夫です！楽しみにしています。",
    imageUrl: null,
    isOwn: false,
  },
];
